"""
Configuration utilities for modifying Calimero node config files.

This module provides shared utilities for both DockerManager and BinaryManager
to configure Calimero nodes consistently.
"""

import ipaddress
import re
import stat
import uuid
from pathlib import Path
from typing import Optional, Union

import toml
from rich.console import Console

console = Console()

# A libp2p peer ID rendered in base58btc (the alphabet excludes 0/O/I/l and any
# character that could break a multiaddr — no '/', no whitespace, no brackets).
# Real peer IDs are ~46 chars (CIDv0 `Qm…`) up to ~53 (`12D3KooW…` for Ed25519);
# 46 is a safe lower bound.
_PEER_ID_RE = re.compile(r"^[1-9A-HJ-NP-Za-km-z]{46,}$")


def _valid_ipv4(addr: str) -> bool:
    """True if ``addr`` is a syntactically valid IPv4 address."""
    try:
        return isinstance(ipaddress.ip_address(addr), ipaddress.IPv4Address)
    except ValueError:
        return False


def set_nested_config(config: dict, key: str, value, log: bool = True) -> None:
    """
    Set nested configuration value using dot notation.

    Args:
        config: The configuration dictionary to modify
        key: Dot-separated key path (e.g., "bootstrap.nodes")
        value: The value to set
        log: Whether to log the change (default True)

    Raises:
        TypeError: If an intermediate key exists but is not a dict
    """
    keys = key.split(".")
    current = config
    for k in keys[:-1]:
        if k not in current:
            current[k] = {}
        elif not isinstance(current[k], dict):
            raise TypeError(f"Cannot set nested key: '{k}' is not a dict")
        current = current[k]

    current[keys[-1]] = value
    if log:
        console.print(f"[cyan]  {key} = {value}[/cyan]")


def apply_bootstrap_nodes(
    config_file: Union[Path, str],
    node_name: str,
    bootstrap_nodes: list[str],
) -> bool:
    """
    Apply bootstrap nodes configuration to a config file.

    Args:
        config_file: Path to the config.toml file (Path or str)
        node_name: Name of the node (for logging)
        bootstrap_nodes: List of bootstrap node addresses
    """
    try:
        config_path = Path(config_file)
        if not config_path.exists():
            console.print(f"[yellow]Config file not found: {config_file}[/yellow]")
            return False

        with open(config_path, encoding="utf-8") as f:
            config = toml.load(f)

        set_nested_config(config, "bootstrap.nodes", bootstrap_nodes)

        # Ensure file is writable
        config_path.chmod(config_path.stat().st_mode | stat.S_IWUSR)

        with open(config_path, "w", encoding="utf-8") as f:
            toml.dump(config, f)

        console.print(
            f"[green]✓ Applied bootstrap nodes to {node_name} ({len(bootstrap_nodes)} nodes)[/green]"
        )
        return True

    except Exception as e:
        console.print(
            f"[red]✗ Failed to apply bootstrap nodes to {node_name}: {e}[/red]"
        )
        return False


def apply_mdns_setting(
    config_file: Union[Path, str],
    node_name: str,
    enabled: bool,
) -> bool:
    """Force discovery.mdns to a specific value in a node's config.toml.

    Without this, a single Docker bridge lets containers find each other via
    mDNS — relay-recovery test paths become no-ops. Workflows running fault
    injection should set mdns=false so the rendezvous/relay code path is
    actually exercised.
    """
    try:
        config_path = Path(config_file)
        if not config_path.exists():
            console.print(f"[yellow]Config file not found: {config_file}[/yellow]")
            return False

        with open(config_path, encoding="utf-8") as f:
            config = toml.load(f)

        set_nested_config(config, "discovery.mdns", enabled)

        config_path.chmod(config_path.stat().st_mode | stat.S_IWUSR)
        with open(config_path, "w", encoding="utf-8") as f:
            toml.dump(config, f)

        console.print(f"[green]✓ Set discovery.mdns={enabled} for {node_name}[/green]")
        return True

    except Exception as e:
        console.print(f"[red]✗ Failed to set mdns for {node_name}: {e}[/red]")
        return False


def read_peer_id(config_file: Union[Path, str]) -> Optional[str]:
    """
    Read the libp2p peer ID from a node's config.toml.

    The peer ID is generated by ``merod init`` and written to the ``[identity]``
    table of ``config.toml``. It is available on disk before ``merod run`` is
    ever started, so callers can use it to wire up bootstrap-peer lists for a
    cluster.

    Args:
        config_file: Path to the config.toml file (Path or str)

    Returns:
        The peer ID string, or ``None`` if it could not be read.
    """
    try:
        config_path = Path(config_file)
        if not config_path.exists():
            console.print(f"[yellow]Config file not found: {config_file}[/yellow]")
            return None

        with open(config_path, encoding="utf-8") as f:
            config = toml.load(f)

        peer_id = config.get("identity", {}).get("peer_id")
        if not peer_id:
            console.print(
                f"[yellow]No identity.peer_id found in {config_file}[/yellow]"
            )
            return None
        return peer_id

    except Exception as e:
        console.print(f"[red]✗ Failed to read peer ID from {config_file}: {e}[/red]")
        return None


def build_sibling_bootstrap_addrs(
    node_name: str,
    peers_by_name: dict[str, Optional[tuple[str, str]]],
    p2p_port: int,
    existing: Optional[list[str]] = None,
) -> list[str]:
    """
    Build the ``bootstrap.nodes`` list for ``node_name`` from its siblings.

    For every *other* node in ``peers_by_name`` with a known ``(ip, peer_id)``,
    emit both a TCP and a QUIC ``/ip4/<ip>/.../p2p/<peer_id>`` multiaddr. IPs are
    used (not ``/dns4/<container>``) because merod's libp2p swarm is built
    without a DNS transport, so it cannot dial ``/dns4/`` addresses. Any
    ``existing`` entries (e.g. an explicit ``bootstrap_nodes:`` list from the
    workflow) are preserved at the front; siblings are appended without
    introducing duplicates. Entries with a malformed IP or peer ID are skipped.

    Args:
        node_name: The node whose bootstrap list is being built.
        peers_by_name: Mapping of node/container name -> ``(ipv4, peer_id)`` (or
            ``None`` if either could not be determined).
        p2p_port: The libp2p swarm port the nodes listen on (inside the network).
        existing: Optional pre-existing bootstrap addresses to keep.

    Returns:
        The ordered, de-duplicated list of bootstrap multiaddrs.
    """
    addrs: list[str] = list(existing) if existing else []
    seen = set(addrs)
    for other_name, endpoint in peers_by_name.items():
        if other_name == node_name or not endpoint:
            continue
        ip, peer_id = endpoint
        if (
            not ip
            or not peer_id
            or not _valid_ipv4(ip)
            or not _PEER_ID_RE.match(peer_id)
        ):
            console.print(
                f"[yellow]⚠️  Skipping bootstrap peer with unexpected "
                f"ip/peer-id: {other_name} -> {ip!r} / {peer_id!r}[/yellow]"
            )
            continue
        for addr in (
            f"/ip4/{ip}/tcp/{p2p_port}/p2p/{peer_id}",
            f"/ip4/{ip}/udp/{p2p_port}/quic-v1/p2p/{peer_id}",
        ):
            if addr not in seen:
                addrs.append(addr)
                seen.add(addr)
    return addrs


def apply_e2e_defaults(
    config_file: Union[Path, str],
    node_name: str,
    workflow_id: Optional[str] = None,
    preserve_default_bootstrap: bool = False,
) -> bool:
    """
    Apply e2e-style defaults for reliable testing.

    Args:
        config_file: Path to the config.toml file (Path or str)
        node_name: Name of the node (for logging)
        workflow_id: Optional workflow ID for test isolation. Generated if not provided.
        preserve_default_bootstrap: When True, skip clearing `bootstrap.nodes`,
            leaving whatever `merod init` wrote (the public devnet boot-node).
            Off by default so the e2e defaults remain isolated from any
            outside network; opt-in for workflows that explicitly want a
            stable rendezvous server outside the test cluster.
    """
    try:
        # Generate unique workflow ID if not provided
        if not workflow_id:
            workflow_id = str(uuid.uuid4())[:8]

        config_path = Path(config_file)
        if not config_path.exists():
            console.print(f"[yellow]Config file not found: {config_file}[/yellow]")
            return False

        # Load existing config
        with open(config_path, encoding="utf-8") as f:
            config = toml.load(f)

        # Apply e2e-style defaults for reliable testing
        # Note: Only bootstrap, discovery, and sync settings are configured here.
        # Protocol-specific config (Ethereum, ICP, etc.) should be handled separately.
        e2e_config = {}

        # By default, clear bootstrap.nodes to fully isolate the cluster
        # from any outside network. Workflows can opt out via the
        # `preserve_default_bootstrap` field to keep whatever `merod
        # init` wrote (the public devnet boot-node) as a stable
        # rendezvous server.
        if not preserve_default_bootstrap:
            e2e_config["bootstrap.nodes"] = []

        e2e_config.update(
            {
                # Use unique rendezvous namespace per workflow (like e2e tests)
                "discovery.rendezvous.namespace": f"calimero/merobox-tests/{workflow_id}",
                # Keep mDNS as backup (like e2e tests)
                "discovery.mdns": True,
                # Aggressive sync settings from e2e tests for reliable testing
                "sync.timeout_ms": 30000,  # 30s timeout (matches production)
                # 500ms between syncs (very aggressive for tests)
                "sync.interval_ms": 500,
                # 1s periodic checks (ensures rapid sync in tests)
                "sync.frequency_ms": 1000,
            }
        )

        # Apply each configuration
        for key, value in e2e_config.items():
            set_nested_config(config, key, value)

        # Ensure file is writable
        config_path.chmod(config_path.stat().st_mode | stat.S_IWUSR)

        # Write back to file
        with open(config_path, "w", encoding="utf-8") as f:
            toml.dump(config, f)

        console.print(
            f"[green]✓ Applied e2e-style defaults to {node_name} (workflow: {workflow_id})[/green]"
        )
        return True

    except Exception as e:
        console.print(f"[red]✗ Failed to apply e2e defaults to {node_name}: {e}[/red]")
        return False
